import os
import subprocess

from SCons.Script import Import

Import("env")


def _git_output(args):
    try:
        return subprocess.check_output(
            args,
            cwd=env["PROJECT_DIR"],
            stderr=subprocess.DEVNULL,
        ).decode("utf-8").strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return None

hash_value = _git_output(["git", "rev-parse", "--short", "HEAD"]) or "unknown"
tag_value = _git_output(["git", "describe", "--tags", "--exact-match"])
if tag_value:
    ref_value = tag_value
else:
    ref_value = _git_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]) or "unknown"

commit_time = _git_output(["git", "show", "-s", "--format=%cI", "HEAD"]) or "unknown"
dirty_output = _git_output(["git", "status", "--porcelain"])
dirty_flag = bool(dirty_output)

def _clamp(text: str, width: int, pad: bool = True) -> str:
    if len(text) > width:
        text = text[:width]
    if pad:
        text = text.ljust(width)
    return text

display_hash = hash_value
if dirty_flag and not display_hash.endswith("+"):
    display_hash += "+"

git_line0 = _clamp(f"git: {display_hash}", 16)
git_line1 = _clamp(ref_value, 16)

if commit_time != "unknown" and len(commit_time) >= 10:
    date_part = commit_time[:10]
else:
    date_part = "unknown"

if commit_time != "unknown" and len(commit_time) >= 19:
    time_part = commit_time[11:19]
elif commit_time != "unknown" and len(commit_time) > 11:
    time_part = commit_time[11:]
else:
    time_part = "unknown"

commit_date_line = _clamp(f"Date: {date_part}", 16)
commit_time_line = _clamp(f"Time: {time_part}", 16)


def _escape_c(text: str) -> str:
    return text.replace('\\', '\\\\').replace('"', '\\"')


generated_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
os.makedirs(generated_dir, exist_ok=True)
header_path = os.path.join(generated_dir, "version_info_data.hpp")

with open(header_path, "w", encoding="utf-8") as header:
    header.write("// Auto-generated by scripts/git_version.py\n")
    header.write("#pragma once\n")
    header.write("#define VERSION_INFO_HAVE_GENERATED 1\n")
    header.write("namespace version_generated {\n")
    header.write(f"inline constexpr bool kGitIsTag = {'true' if tag_value else 'false'};\n")
    header.write(f"inline constexpr bool kGitDirty = {'true' if dirty_flag else 'false'};\n")
    header.write(f"inline constexpr char kGitHashStr[] = \"{_escape_c(display_hash)}\";\n")
    header.write(f"inline constexpr char kGitRefStr[] = \"{_escape_c(ref_value)}\";\n")
    header.write(f"inline constexpr char kGitCommitIso[] = \"{_escape_c(commit_time)}\";\n")
    header.write(f"inline constexpr char kGitScreenLine0[] = \"{_escape_c(git_line0)}\";\n")
    header.write(f"inline constexpr char kGitScreenLine1[] = \"{_escape_c(git_line1)}\";\n")
    header.write(f"inline constexpr char kGitDateLine[] = \"{_escape_c(commit_date_line)}\";\n")
    header.write(f"inline constexpr char kGitTimeLine[] = \"{_escape_c(commit_time_line)}\";\n")
    header.write("}\n")

env.Append(CPPPATH=[generated_dir])
